# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.0.3
_src_path: gh:object-Object/hexdummy
author: MoonlitJolteon
capitalize_platforms: false
classname: Hexkeys
default_branch: main
description: 'Hex Keys: Accessing your inner thoughts'
display_name: Hex Keys
github_repo: hex-keys-addon
hexcasting_version: 0.10.3
homepage_url: https://hexkeys.munebase.dev
initial_mod_version: 0.0.1
java_version: 17
license: MIT
mappings: '"net.fabricmc:yarn:1.19.2+build.28:v2"'
modid: hexkeys
package: dev.munebase.hexkeys
sources_url: https://github.com/MoonlitJolteon/hex-keys-addon
