# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.10
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
author: MoonlitJolteon
book_id: hexkeys:hexkeysbook
default_branch: main
github_repo: hex-keys-addon
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: HexkeysModPlugin
hexdoc_plugin_classname: HexkeysPlugin
java_lang:
    ext: java
    src: java
java_package: dev/munebase/hexkeys
mod_display_name: Hex Keys
modid: hexkeys
multiloader: true
package_export_root: doc/src/hexdoc_hexkeys/_export
package_name: hexdoc-hexkeys
package_slug: hexdoc_hexkeys
package_src: doc/src/hexdoc_hexkeys
pages_url: https://moonlitjolteon.github.io/hex-keys-addon
pattern_regex:
    per_world_value: registerPerWorld
    regex: (?P<is_per_world>register|registerPerWorld)\(HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)\),\s*"(?P<name>[^"]+)"?
pattern_registry: registry/HexkeysPatternRegistry.java
